### ISSUE TITLE
install.sh git hook feature complains when used as submodule

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#1026]
![image](https://user-images.githubusercontent.com/9429556/233899087-29dfeb06-da4b-4f71-93f6-7511bd26c22f.png)

https://github.com/nanaian/merlon/blob/310679be162f0f053e9cce9e0e0bea721c327804/src/new.rs#L91

**Comment by Gorialis** [comment]
This looks like it's probably a bug with python_githooks. I will look into it and raise it with them if I can figure out how to fix for it.

**Comment by Gorialis** [comment]
This bug is caused by `python_githooks` attempting to use the CWD to both find the config and register the hooks. Adding hooks for submodules is possible - but it has to be part of the parent repository (where `.git/hooks` is for the parent repo, `.git/modules/papermario/hooks` or etc is for the submodule - you can locate the correct directory with `git rev-parse --git-path hooks` when in the respective directory). I will PR to fix it on their end and then cross-reference the PR for tracking.

**Comment by Gorialis** [comment]
The maintainer of `python_githooks` seems to be rather inactive, the module has other problems than this, and I figured out an easier way to do this hook anyway, so by request I'm PRing in an alternate simpler approach.
