### ISSUE TITLE
Another issue with building - "ninja: error: loading 'build.ninja': No such file or directory"

### ISSUE THREAD

**Issue by SomeRandoPeep** [pmret/papermario#1192]
Now, I installed everything I needed to compile and build the game. I am running on Ubuntu, and have Ninja installed and tried to do so both ways just to make sure. With this last step whenever I type ninja in the terminal I get the error "ninja: error: loading 'build.ninja': No such file or directory". I've looked around for a bit to check fixes for this but none of them are working. I don't know what I did wrong as I followed all the instructions. At least I'm not building Arch Linux lol.

**Comment by ethteck** [comment]
Feel free to comment your original issue in the future. I think you haven't successfully run configure yet, as that is what generates build.ninja

**Comment by SomeRandoPeep** [comment]
I checked again, and yeah this is getting more confusing...

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, you need to source
the corresponding env file under $HOME/.cargo.

This is usually done by running one of the following (note the leading DOT):
. "$HOME/.cargo/env"            # For sh/bash/zsh/ash/dash/pdksh
source "$HOME/.cargo/env.fish"  # For fish

**Comment by Brotenko** [comment]
Where did you got those 3 paragraphs from, is my biggest question at the moment 🤔 

And what is the current error you are getting after running `./configure`? Normally that should generate build.ninja for you, but if it doesn't, then there should be a different error message leading to it.

**Comment by Brotenko** [comment]
On a different note though, since there is a lot of confusion about the topic of decomp and PC ports: If you want to set up this repo and the build system in hopes of it spitting out a PC Port at the end, or anything that is playable natively, then this isn't the right place. So far there are no projects for a PC port of the game, nor a functional Recomp.

However, if you want to contribute to the project, or are looking to do something besides that with the decomp, I am more than happy to help with setting up. In that case I would recommend joining our Discord tho, since communication about this will be a lot smoother and faster than via Github Issue comment :D

**Comment by ethteck** [comment]
Can you share the output of running configure --clean @SomeRandoPeep ?

**Comment by SomeRandoPeep** [comment]
Using that command made the terminal look for the rom I had, it completely compiled the rom with no errors I guess.

**Comment by ethteck** [comment]
awesome! let us know if you have other questions in the future, and I'll close this for now
